package handlers_test

import (
	"net/http"
	"strings"
	"testing"
)

func TestGeneratorDockerSuccess(t *testing.T) {
	f := newTestFixture(t)
	tok := loginToken(t, f)

	rec := f.do(t, http.MethodPost, "/generator/docker", map[string]any{
		"name":     "app",
		"image":    "node:20",
		"detached": true,
		"restart":  "unless-stopped",
		"ports": []map[string]any{
			{"host": 8080, "container": 80, "protocol": "tcp"},
		},
	}, map[string]string{
		"Authorization": "Bearer " + tok,
	})

	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusOK, rec.Body.String())
	}
	body := parseJSON(t, rec)
	cmd, _ := body["command"].(string)
	if !strings.Contains(cmd, "--name 'app'") {
		t.Errorf("command should contain --name 'app', got: %s", cmd)
	}
	if !strings.Contains(cmd, "'node:20'") {
		t.Errorf("command should contain 'node:20', got: %s", cmd)
	}
}

func TestGeneratorDockerMissingName(t *testing.T) {
	f := newTestFixture(t)
	tok := loginToken(t, f)

	rec := f.do(t, http.MethodPost, "/generator/docker", map[string]any{
		"image": "node:20",
	}, map[string]string{
		"Authorization": "Bearer " + tok,
	})
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusBadRequest, rec.Body.String())
	}
}

func TestGeneratorPM2Success(t *testing.T) {
	f := newTestFixture(t)
	tok := loginToken(t, f)

	rec := f.do(t, http.MethodPost, "/generator/pm2", map[string]any{
		"name":   "api",
		"script": "/srv/server.js",
	}, map[string]string{
		"Authorization": "Bearer " + tok,
	})
	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusOK, rec.Body.String())
	}
	body := parseJSON(t, rec)
	cmd, _ := body["command"].(string)
	if !strings.Contains(cmd, "pm2 start '/srv/server.js'") {
		t.Errorf("command should contain pm2 start '/srv/server.js', got: %s", cmd)
	}
}

func TestGeneratorComposeSuccess(t *testing.T) {
	f := newTestFixture(t)
	tok := loginToken(t, f)

	rec := f.do(t, http.MethodPost, "/generator/compose", map[string]any{
		"services": []map[string]any{
			{"name": "web", "image": "nginx:1.27"},
		},
	}, map[string]string{
		"Authorization": "Bearer " + tok,
	})
	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusOK, rec.Body.String())
	}
	body := parseJSON(t, rec)
	yaml, _ := body["yaml"].(string)
	if !strings.Contains(yaml, "image: nginx:1.27") {
		t.Errorf("yaml should contain `image: nginx:1.27`, got: %s", yaml)
	}
	if !strings.Contains(yaml, "# generated by vps-dashboard") {
		t.Errorf("yaml should contain header, got: %s", yaml)
	}
}

func TestGeneratorNginxSuccess(t *testing.T) {
	f := newTestFixture(t)
	tok := loginToken(t, f)

	rec := f.do(t, http.MethodPost, "/generator/nginx", map[string]any{
		"domain":        "x.test",
		"upstream_host": "127.0.0.1",
		"upstream_port": 3001,
	}, map[string]string{
		"Authorization": "Bearer " + tok,
	})
	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusOK, rec.Body.String())
	}
	body := parseJSON(t, rec)
	cfg, _ := body["config"].(string)
	if !strings.Contains(cfg, "server_name x.test;") {
		t.Errorf("config should contain `server_name x.test;`, got: %s", cfg)
	}
	if !strings.Contains(cfg, "proxy_pass http://127.0.0.1:3001;") {
		t.Errorf("config should contain proxy_pass to upstream, got: %s", cfg)
	}
}

func TestGeneratorUnauthorized(t *testing.T) {
	f := newTestFixture(t)
	rec := f.do(t, http.MethodPost, "/generator/docker", map[string]any{
		"name":  "app",
		"image": "node:20",
	}, nil)
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusUnauthorized, rec.Body.String())
	}
}

func TestGeneratorTunnelsEmpty(t *testing.T) {
	// On dev mac /etc/cloudflared rarely exists; the route must respond 200
	// with an empty list rather than crashing.
	f := newTestFixture(t)
	tok := loginToken(t, f)
	rec := f.do(t, http.MethodGet, "/system/tunnels", nil, map[string]string{
		"Authorization": "Bearer " + tok,
	})
	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d want %d body=%s", rec.Code, http.StatusOK, rec.Body.String())
	}
	body := parseJSON(t, rec)
	if _, ok := body["data"]; !ok {
		t.Errorf("expected `data` key in body, got %v", body)
	}
}
