package generator

import (
	"strings"
	"testing"
)

func TestDockerRunBasic(t *testing.T) {
	got, err := DockerRun(DockerRunOpts{
		Name:     "webapp",
		Image:    "node:20-alpine",
		Detached: true,
		Restart:  "unless-stopped",
		Ports: []PortMapping{
			{Host: 8080, Container: 80, Protocol: "tcp"},
		},
		Volumes: []VolumeMapping{
			{Host: "/data", Container: "/var/lib/app", Mode: "rw"},
		},
		Env: []EnvVar{
			{Key: "NODE_ENV", Value: "production"},
		},
		Command: "node server.js",
	})
	if err != nil {
		t.Fatalf("DockerRun: %v", err)
	}

	wants := []string{
		"docker run -d",
		"--name 'webapp'",
		"--restart unless-stopped",
		"-p '8080:80/tcp'",
		"-v '/data:/var/lib/app:rw'",
		"-e 'NODE_ENV=production'",
		"'node:20-alpine'",
		"'node server.js'",
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("expected output to contain %q\ngot:\n%s", w, got)
		}
	}
}

func TestDockerRunValidation(t *testing.T) {
	cases := []struct {
		name string
		opts DockerRunOpts
		want string
	}{
		{
			name: "missing name",
			opts: DockerRunOpts{Image: "alpine"},
			want: "name: required",
		},
		{
			name: "missing image",
			opts: DockerRunOpts{Name: "x"},
			want: "image: required",
		},
		{
			name: "bad restart",
			opts: DockerRunOpts{Name: "x", Image: "alpine", Restart: "loop"},
			want: "restart:",
		},
		{
			name: "bad port",
			opts: DockerRunOpts{Name: "x", Image: "alpine",
				Ports: []PortMapping{{Host: 0, Container: 80}}},
			want: "ports[0].host",
		},
		{
			name: "bad protocol",
			opts: DockerRunOpts{Name: "x", Image: "alpine",
				Ports: []PortMapping{{Host: 80, Container: 80, Protocol: "icmp"}}},
			want: "protocol",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := DockerRun(tc.opts)
			if err == nil {
				t.Fatalf("expected error containing %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q should contain %q", err.Error(), tc.want)
			}
		})
	}
}

func TestPM2Start(t *testing.T) {
	got, err := PM2Start(PM2Opts{
		Name:        "api",
		Script:      "/srv/app/server.js",
		Interpreter: "node",
		Instances:   2,
		Watch:       true,
	})
	if err != nil {
		t.Fatalf("PM2Start: %v", err)
	}
	for _, w := range []string{
		"pm2 start '/srv/app/server.js'",
		"--name 'api'",
		"--interpreter 'node'",
		"-i 2",
		"--watch",
	} {
		if !strings.Contains(got, w) {
			t.Errorf("expected output to contain %q\ngot:\n%s", w, got)
		}
	}
}

func TestPM2StartMissingFields(t *testing.T) {
	if _, err := PM2Start(PM2Opts{Script: "x"}); err == nil {
		t.Errorf("expected error for missing name")
	}
	if _, err := PM2Start(PM2Opts{Name: "x"}); err == nil {
		t.Errorf("expected error for missing script")
	}
}

func TestDockerCompose(t *testing.T) {
	got, err := DockerCompose(ComposeOpts{
		Services: []ComposeService{
			{
				Name:    "web",
				Image:   "nginx:1.27",
				Restart: "unless-stopped",
				Ports:   []PortMapping{{Host: 8080, Container: 80, Protocol: "tcp"}},
				Env:     []EnvVar{{Key: "FOO", Value: "bar"}},
			},
		},
	})
	if err != nil {
		t.Fatalf("DockerCompose: %v", err)
	}
	for _, w := range []string{
		"# generated by vps-dashboard",
		"version:",
		"3.8",
		"services:",
		"web:",
		"image: nginx:1.27",
		"restart: unless-stopped",
		"8080:80/tcp",
		"FOO=bar",
	} {
		if !strings.Contains(got, w) {
			t.Errorf("expected output to contain %q\ngot:\n%s", w, got)
		}
	}
}

func TestDockerComposeRequiresAtLeastOneService(t *testing.T) {
	if _, err := DockerCompose(ComposeOpts{}); err == nil {
		t.Errorf("expected error for empty services")
	}
}

func TestNginxReverseProxyPlain(t *testing.T) {
	got, err := NginxReverseProxy(NginxOpts{
		Domain:       "x.test",
		UpstreamHost: "127.0.0.1",
		UpstreamPort: 3001,
	})
	if err != nil {
		t.Fatalf("NginxReverseProxy: %v", err)
	}
	for _, w := range []string{
		"server {",
		"listen 80;",
		"server_name x.test;",
		"proxy_pass http://127.0.0.1:3001;",
		"X-Forwarded-For $proxy_add_x_forwarded_for;",
	} {
		if !strings.Contains(got, w) {
			t.Errorf("expected output to contain %q\ngot:\n%s", w, got)
		}
	}
	if strings.Contains(got, "listen 443") {
		t.Errorf("plain proxy should not contain `listen 443`\ngot:\n%s", got)
	}
}

func TestNginxReverseProxySSL(t *testing.T) {
	got, err := NginxReverseProxy(NginxOpts{
		Domain:          "x.test",
		UpstreamHost:    "127.0.0.1",
		UpstreamPort:    3001,
		EnableSSL:       true,
		SSLCertPath:     "/etc/letsencrypt/live/x.test/fullchain.pem",
		SSLKeyPath:      "/etc/letsencrypt/live/x.test/privkey.pem",
		EnableWebsocket: true,
	})
	if err != nil {
		t.Fatalf("NginxReverseProxy ssl: %v", err)
	}
	for _, w := range []string{
		"listen 80;",
		"return 301 https://$host$request_uri;",
		"listen 443 ssl;",
		"ssl_certificate /etc/letsencrypt/live/x.test/fullchain.pem;",
		"ssl_certificate_key /etc/letsencrypt/live/x.test/privkey.pem;",
		"proxy_set_header Upgrade $http_upgrade;",
	} {
		if !strings.Contains(got, w) {
			t.Errorf("expected output to contain %q\ngot:\n%s", w, got)
		}
	}
}

func TestNginxValidation(t *testing.T) {
	cases := []struct {
		name string
		opts NginxOpts
		want string
	}{
		{
			name: "missing domain",
			opts: NginxOpts{UpstreamHost: "x", UpstreamPort: 80},
			want: "domain: required",
		},
		{
			name: "missing upstream host",
			opts: NginxOpts{Domain: "x", UpstreamPort: 80},
			want: "upstream_host: required",
		},
		{
			name: "port out of range",
			opts: NginxOpts{Domain: "x", UpstreamHost: "y", UpstreamPort: 70000},
			want: "upstream_port: out of range",
		},
		{
			name: "ssl missing cert",
			opts: NginxOpts{Domain: "x", UpstreamHost: "y", UpstreamPort: 80, EnableSSL: true},
			want: "ssl_cert_path",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := NginxReverseProxy(tc.opts)
			if err == nil {
				t.Fatalf("expected error containing %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q should contain %q", err.Error(), tc.want)
			}
		})
	}
}

func TestShellQuote(t *testing.T) {
	cases := map[string]string{
		"":            "''",
		"hello":       "'hello'",
		"a b":         "'a b'",
		"it's":        `'it'\''s'`,
		"$(whoami)":   "'$(whoami)'",
		"; rm -rf /":  "'; rm -rf /'",
	}
	for in, want := range cases {
		if got := shellQuote(in); got != want {
			t.Errorf("shellQuote(%q): got %q want %q", in, got, want)
		}
	}
}
